### ISSUE TITLE
The steam controller Layout not found

### ISSUE THREAD

**Issue by Kolazig** [Ryac1/Ryac_TW_Steamdeck_UI#2]
Hello,

I follow the instruction provided (rename to World of Warcraft). There are a list of layout but i don't find he Ryac one. Maybe it has been deleted.

PS: Love your work

**Comment by Ryac1** [comment]
Hi, Thank you :)
Can you try when standing on 'Community Layouts' (i think thats what its named) and then press X to show all layouts? i heard that sometimes works. Otherwise try to rename the game to "Turtle wow" i added it to that aswell ( might need a quick restart first)

**Comment by Kolazig** [comment]
I dont remenber if i try to press X of the 'Community Layouts'. I will try tonight (I am at work).
I already try to rename "Turtle wow". I didn't find it (maybe i need to press X also).

I'll keep you informed

Thanks for the fast response.

**Comment by Ryac1** [comment]
Ok, if not i can try uploading it again tonight

**Comment by Kolazig** [comment]
I use the "press X" tips, i find the configuration, works well.

Just a remark, i dont find how select a target. I change your configuration just a little bit to do.
How do you select (or switch) enemy?

**Comment by Ryac1** [comment]
Ah great, good to hear.
I make a macro and put it on the actionbar on L1 button, you can see it here: https://github.com/Ryac1/Ryac_TW_Steamdeck_UI#target-macro

**Comment by Kolazig** [comment]
Oh my, i am blind xD thank you!

**Comment by Ryac1** [comment]
No problem 👍
